# Generated by Django 4.2.5 on 2023-09-23 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0002_remove_author_bio_article_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='magazine',
            name='editor',
        ),
    ]
