# Generated by Django 4.2.5 on 2023-09-23 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0003_remove_magazine_editor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Task.author'),
        ),
        migrations.AlterField(
            model_name='article',
            name='magazines',
            field=models.ManyToManyField(default='', to='Task.magazine'),
        ),
    ]
